---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: railos
  labels:
    app: alertmanager
    app.kubernetes.io/part-of: railos-pilot
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
      protocol: TCP
