---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: railos
  labels:
    app: elasticsearch
    app.kubernetes.io/part-of: railos-pilot
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: railos
  labels:
    app: elasticsearch
    app.kubernetes.io/part-of: railos-pilot
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: transport
      port: 9300
      targetPort: transport
